[tools]
bat = "0.26"
claude = "latest"
codex = "latest"
eza = "0.23"
fd = "10"
fzf = "0.73"
go = "1.26"
lazygit = "0.62"
neovim = "0.12"
node = "24"
opencode = "latest"
python = "3.14"
ripgrep = "15"
ruby = "4.0"
rust = "stable"
shellcheck = "0.11"
yazi = "26"
yarn = "4"
zoxide = "0.9"
